export const INITIALIZE_USER = "INITIALIZE_USER";
export const ADD_MESSAGE = "ADD_MESSAGE";
export const ADD_SUGGESTIONS = "SUGGESTIONS"; 
export const ADD_CONTACTS = "ADD_CONTACTS";
export const UPDATE_ACTIVE_THREAD = "UPDATE_ACTIVE_THREAD";
export const PUSH_NEW_THREAD = "PUSH_NEW_THREAD";
export const UPDATE_CONTACT_CONVO_ID = "UPDATE_CONTACT_CONVO_ID";
export const ADD_BLOCKED_LIST = "ADD_BLOCKED_LIST";
export const REMOVE_BLOCKED_USER = "REMOVE_BLOCKED_USER";
export const UPDATE_UNREAD = "UPDATE_UNREAD";
export const ADD_FRIENDSLIST = "ADD_FRIENDSLIST";

